---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: default

---
# kubectl create role secret-modifier --verb=get,list,watch,create,update,patch,delete,deletecollection --resource=secret
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-modifier
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - patch

---
# kubectl create rolebinding vault-secret-modifier-binding --role=secret-modifier --serviceaccount=default:vault-auth
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-secret-modifier-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-modifier
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: default